### ISSUE TITLE
Student DBMS doesnot validate type of input given

### ISSUE THREAD

**Issue by Anish-M-code** [Raagul26/Simple-Student-DBMS#1]
![Screenshot_2020-07-18_21-11-41](https://user-images.githubusercontent.com/58029804/87856261-7e5cf300-c90d-11ea-81f1-b99e127e4357.png)
By giving input as given in the picture the DBMS accepts it without throwing any error.
![Screenshot_2020-07-18_21-12-20](https://user-images.githubusercontent.com/58029804/87856272-97fe3a80-c90d-11ea-9248-891734f57d7a.png)
however it fails to retrive the data even when valid number and valid registration done.
Testing done in debian 10 testing.

**Comment by Raagul26** [comment]
To check result you will need to add regno, dob, marks manually in database. That's only I provided already created results in readme file. Plz check that.

**Comment by Raagul26** [comment]
Not added validation. Will add in future.
Thank you for your support.
